name: capi-fastly-cache-purger CI

on:
  push:
    branches:
      - main
  pull_request:
    paths-ignore:
      - 'lambdas/facia-fastly-cache-purger/**'
      - '**.md' # Exclude markdown files
      - .nvmrc
  workflow_dispatch:

# allow queued workflows to interrupt previous runs
concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.ref }}
  cancel-in-progress: true

permissions:
  id-token: write
  contents: read

jobs:
  CI_capi_purger:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      pull-requests: write # required since guardian/actions-riff-raff@v3
    steps:
      - uses: actions/checkout@v5

      - name: Prepare Node
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'yarn'

      - name: Install dependencies
        working-directory: ./lambdas/capi-fastly-cache-purger
        run: yarn install --frozen-lockfile

        # todo add linting
      - name: Run tests
        working-directory: ./lambdas/capi-fastly-cache-purger
        run: yarn test

      - name: Build
        working-directory: ./lambdas/capi-fastly-cache-purger
        run: yarn build

      - name: Create Distribution Package
        working-directory: ./lambdas/capi-fastly-cache-purger
        run: yarn dist

      - name: CDK synth
        working-directory: ./cdk
        run: |
          yarn install --frozen-lockfile
          yarn test
          yarn synth:capi

      - name: Upload artifacts to riff-raff
        uses: guardian/actions-riff-raff@v4
        with:
          projectName: mobile::mobile-capi-fastly-cache-purger
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          roleArn: ${{ secrets.GU_RIFF_RAFF_ROLE_ARN }}
          configPath: cdk/cdk.out/mobile-capi-fastly-cache-purger/riff-raff.yaml
          contentDirectories: |
            cdk.out/mobile-capi-fastly-cache-purger:
              - cdk/cdk.out/mobile-capi-fastly-cache-purger
            mobile-capi-fastly-cache-purger:
              - mobile-capi-fastly-cache-purger-lambda.zip
